In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import sklearn
from IPython.display import display
#Dates (month/day/year): 01/01/1982 through 03/28/2020 
#Location: Latitude  50.25   Longitude 20.75 

In [3]:
raw_df = pd.read_csv("LTArea_data.txt")
raw_df

year  day_of_year  tot_precipitation  surface_pressure  temp_at2m  \
0      1982            1               0.59             97.35       1.01   
1      1982            2               0.21             98.25      -1.63   
2      1982            3               2.44             98.42      -0.77   
3      1982            4               4.02             97.63       1.38   
4      1982            5               4.38             97.34       1.98   
...     ...          ...                ...               ...        ...   
13962  2020           84               0.00            100.40      -2.20   
13963  2020           85               0.03            100.16      -0.64   
13964  2020           86               0.00             99.70       2.77   
13965  2020           87             -99.00            -99.00     -99.00   
13966  2020           88             -99.00            -99.00     -99.00   

       min_temp_at2m  wind_speed  max_wind_speed  
0               0.06        2.02            2.58  
1              -4.60        2.34            3.37  
2              -4.55        3.10            5.54  
3               1.06        4.30            5.69  
4               0.92        5.14            6.38  
...              ...         ...             ...  
13962          -6.37        3.90            5.97  
13963          -5.50        4.02            6.20  
13964          -3.37        3.35            4.99  
13965         -99.00     -999.00         -999.00  
13966         -99.00     -999.00         -999.00  

[13967 rows x 8 columns]

In [4]:
weather_data_raw = raw_df[["temp_at2m", "min_temp_at2m", "surface_pressure","wind_speed","max_wind_speed"]].copy()
weather_data_names = list(weather_data_raw.columns)

In [5]:
weather_data = weather_data_raw.to_numpy()
print(weather_data)

[[ 1.010e+00  6.000e-02  9.735e+01  2.020e+00  2.580e+00]
 [-1.630e+00 -4.600e+00  9.825e+01  2.340e+00  3.370e+00]
 [-7.700e-01 -4.550e+00  9.842e+01  3.100e+00  5.540e+00]
 ...
 [ 2.770e+00 -3.370e+00  9.970e+01  3.350e+00  4.990e+00]
 [-9.900e+01 -9.900e+01 -9.900e+01 -9.990e+02 -9.990e+02]
 [-9.900e+01 -9.900e+01 -9.900e+01 -9.990e+02 -9.990e+02]]


In [6]:
target_data_raw = raw_df["tot_precipitation"].to_list()
target_data_names = ["Znikome opady lub brak opadów","Lekkie opady","Intensywne opady"]

In [7]:
target_data = []
for precipitation in target_data_raw:
    if precipitation < 5:
        target_data.append(0)
    elif precipitation >= 5 and precipitation < 12:
        target_data.append(1)
    else:
        target_data.append(2)

In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(weather_data, target_data, random_state = 0)

In [9]:
#training_df = pd.DataFrame(X_train, columns = weather_data_names)
#pd.plotting.scatter_matrix(training_df, c=y_train)

In [10]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors=9)

In [11]:
knn.fit(X_train, y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=9, p=2,
                     weights='uniform')

In [12]:
print("Test score:", knn.score(X_test,y_test))

Test score: 0.8888888888888888


In [13]:
X_new = np.array([[17, 2, 102.5, 9, 17]])#temp,min_temp,surf_press,wind_speed,max_wind_speed
prediction = knn.predict(X_new)
print("Prognoza:", target_data_names[prediction[0]])

Prognoza: Znikome opady lub brak opadów
